### PR TITLE
Mirror the target control of ObjectNavFragment if front facing camera is used

### PR DESCRIPTION
**Pull request by yijunwu**
When front facing camera is used, the target control of ObjectNavFragment should be mirrored otherwise the bot can't follow the target object. See the issue [385](https://github.com/isl-org/OpenBot/issues/385) for detail

### CODE REVIEW

**Comment by thias15** [comment]
The convention for the front camera varies across phones. How about adding an icon to mirror controls next to the camera flip icon.

**Comment by yijunwu** [comment]
OK, I haven't tried phones other than Samsung's. Maybe a better solution would be to detect the convention for the phone automatically, and set default value accordingly, in addition to adding icon to mirror control? Not sure if it's detectable. Before figuring out that, adding icon to mirror control can be a basic solution. I'll add some more commits soon

**Comment by yijunwu** [comment]
I've added more commits. It should be ok now.
image
image

**Comment by yijunwu** [comment]
I adjusted the layout and appearance of icons, now it looks like this: 
6830d259c0e1cca88ef2e2368520496
fa1deaea6ead352cafed02663e759dd

**Review by desy0305 — APPROVED** [review]
ok

**Review by thias15 — APPROVED** [review]

**Comment by hardikgarg02** [comment]
I have fixed the UI for the fragment. Could you review and replace below file named `fragment_object_nav.xml` in the path `robot/src/main/res/layout-land` directory.
[fragment_object_nav.xml.zip](https://github.com/isl-org/OpenBot/files/13784523/fragment_object_nav.xml.zip)

And also replace below file named `fragment_object_nav.xml` in the path `robot/src/main/res/layout` directory.
[fragment_object_nav.xml.zip](https://github.com/isl-org/OpenBot/files/13784567/fragment_object_nav.xml.zip)

**Pull request merged**
