### PR TITLE
Fix dataloader and dependencies

### PR DESCRIPTION
**Pull request by thias15**
- make sure the training environments are consistent across different OS
- improve README to explain setup with GPU
- bugfix in dataloader

### CODE REVIEW

**Review by quentin-leboutet — COMMENTED** [review]
Looks good to me. I'm testing it on W10, Ubuntu 22 and Mac (intel + arm). I will approve this PR as soon as I'm sure everything works on each platform.

**Comment by quentin-leboutet** [comment]
Update: successfully tested on W10 and iOS (apple M1). Did not work out of the box on Ubuntu 22. I had to manually install a specific version the driver (nvidia-driver-495) along with the cuda-toolkit and cudnn packages of the main ubuntu repo:
`sudo apt-get install cuda-toolkit && sudo apt-get install nvidia-driver-510 && sudo apt-get install nvidia-cudnn`

**Comment by thias15** [comment]
I see. Any suggestions how it might work out of the box on Ubuntu? I tested it on a Linux cluster and it worked well there.

**Comment by quentin-leboutet** [comment]
Solved. Adding “`export LD_LIBRARY_PATH=/path/to/anaconda3/envs/openbot/lib:$LD_LIBRARY_PATH`” to the .bashrc to point to the correct versions of the libraries seems to do the trick. I'm validating this PR as not so many changes are required.

**Review by quentin-leboutet — APPROVED** [review]

**Pull request merged**
