### PR TITLE
Use BT SPP wireless connection between microcontroller and Android app.

### PR DESCRIPTION
**Pull request by RoachWZ**
#324 I installed a [Bluetooth module](https://a.co/d/131V4o4) on the car, which can remotely control the car. Use BT SPP wireless connection between microcontroller and Android app.
Bluetooth_module
The app will not to connect automatically, you must use this switch to select Bluetooth device connect/disconnect.
I recorded a demonstration [video](https://www.bilibili.com/video/BV1n3411X7vk) of Bluetooth connection
screen_setting

### CODE REVIEW

**Comment by RoachWZ** [comment]
@RoachWZ
Use BT SPP wireless connection between microcontroller and Android app.
The app will not to connect automatically, you must use this switch to select Bluetooth device connect/disconnect.
screen_settings

**Comment by RoachWZ** [comment]
I installed a Bluetooth module on the car, which can remotely control the car. Use BT SPP wireless connection between microcontroller and Android app.
Bluetooth module
The app will not to connect automatically, you must use this switch to select Bluetooth device connect/disconnect.
screen_setting

**Comment by RoachWZ** [comment]
I recorded a demonstration video of Bluetooth connection
[video](https://www.bilibili.com/video/BV1n3411X7vkl)

**Review by reger24 — COMMENTED** [review]
After adjusting the arduino firmware to accept BT input (via #include <SoftwareSerial.h> and BLTSerial.....) it worked for me.

**Comment by RoachWZ** [comment]
> After adjusting the arduino firmware to accept BT input (via #include <SoftwareSerial.h> and BLTSerial.....) it worked for me.
So you're using ESP32, right? I use the Nano's TX RX to connect with the Bluetooth module. No change arduino firmware.

**Comment by RoachWZ** [comment]
> After adjusting the arduino firmware to accept BT input (via #include <SoftwareSerial.h> and BLTSerial.....) it worked for me.

So you're using ESP32, right? I use the Nano's TX RX to connect with the Bluetooth module. No change arduino firmware

**Comment by reger24** [comment]
@RoachWZ 
> So you're using ESP32, right? I use the Nano's TX RX to connect with the Bluetooth module. No change arduino firmware
not 100% sure but I think mine is called ESP8266 + HC02 (a UNO board)

**Review by reger24 — APPROVED** [review]
Works for me (as mentioned in earlier comment, after adjusting firmware (ESP32) with Softwareserial.h to accept BT).
It's a nice feature (I already was missing, before I purchased a USB cable).
I'd accept the pull request.

**Comment by thias15** [comment]
@RoachWZ, your contribution would still be appreciated. We just need to merge the BLE PR first to support ESP32 and then find a way to select the BT mode. Sorry for the delay in reviewing, but we have been very busy.

**Pull request closed without merging**
