### PR TITLE
Adjust robot speed by a estimated distancefactor.

### PR DESCRIPTION
**Pull request by reger24**
Adjust robot speed (in object tracking mode) by a distance factor estimated from the width of the tracking box
assuming that the tracking box is lage if close to tracked object and apply the factor to the speed control vars.

https://github.com/isl-org/OpenBot/issues/310

### CODE REVIEW

**Comment by thias15** [comment]
Hi @reger24. Thanks for your contribution. Using only the width of the bounding box may be quite specific to the object of choice and the orientation of the phone. For example the ratio between bounding box width and frame width would be quite different if the phone is in landscape or portrait mode and also very different if you track a person vs. a car. I think it would probably be better to use the area (width*height) instead.

**Comment by thias15** [comment]
Also, the style check did not pass. You can fix the style by navigating to the android folder and then executing `./gradlew applyStyle`

**Comment by reger24** [comment]
Hi @thias15 , your point with the orientation dependency is very likely true (as I tested & concentrated on landscape).
I'll try your suggestion using the area and update my proposal/pull-request.
Thanks & Tschüß

**Comment by thias15** [comment]
@reger24 sounds good. You can just push updates to your branch and the PR will be updated automatically.

**Comment by reger24** [comment]
Hi @thias15 ,  https://github.com/isl-org/OpenBot/pull/311/commits/18effda2000304782289548e172a31eaac134c80 is the final change to the 1st implementation of it (if you choose so).
cu

**Comment by thias15** [comment]
Hi @reger24. Sorry for the delay, very busy few months. This looks good, but since it does not work reliably in portrait mode for some classes, how about making this scaling optional? There could be a `on/off` for dynamic speed; its setting could be stored in the shared prefs. What do you think?

**Comment by reger24** [comment]
> Hi @reger24. 
 There could be a `on/off` for dynamic speed; its setting could be stored in the shared prefs. What do you think?

@thias15 sounds good to me (with shared pefs switch), I'll update the pr in the next days.

**Comment by thias15** [comment]
Sorry for being so picky. But ideally the dynamic speed toggle would be only in the ObjectNav GUI since it's specific to that. The settings menu is meant more for global settings like permissions, video streaming mode, robot connection, etc.

**Comment by reger24** [comment]
No problem (was not completley convinced myself about the best place of the option switch), for now I'll try to squeeze it to ObjectNav's bottom sheet - and update PR.

P.S.
BUT
I believe sooner or later it would be benefitial to have a separate settings/preference screen for such option settings (which go into/are stored in openbot_settings.xml) as I foresee some more to come, to make them visible/adjustable (as preference w/o overcrowding bottomsheets) .
So I intend to prepare a **separate** PR 
- with a "Advanced (AI) Settings" or "Detail AI Setting" which make parts of openbot_settings.xml visible
- add a Link to the "Settings" which opens the Advanced Settings screen, with categories for "General (all AI screens)" (eg. CAMERA_SWITCH) and individual (eg. "Object Tracking") for related settings.
  - later (if there are more options)... a button on bottomsheet could also open the Advanced Settings screen

**Review by thias15 — APPROVED** [review]

**Pull request merged**
